"""add flag and environment references to audit logs

Revision ID: 23a65f6d5ce6
Revises: 725dd9b9cbaf
Create Date: 2026-09-20 20:24:40.327303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a65f6d5ce6'
down_revision: Union[str, Sequence[str], None] = '725dd9b9cbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('flag_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'feature_flags', ['flag_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'environments', ['environment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'environment_id')
    op.drop_column('audit_logs', 'flag_id')
    # ### end Alembic commands ###
