"""set audit log foreign keys to null on delete

Revision ID: 5045a8affde2
Revises: 23a65f6d5ce6
Create Date: 2026-09-21 09:57:36.398055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5045a8affde2'
down_revision: Union[str, Sequence[str], None] = '23a65f6d5ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_flag_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_environment_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'feature_flags', ['flag_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_environment_id_fkey'), 'audit_logs', 'environments', ['environment_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_flag_id_fkey'), 'audit_logs', 'feature_flags', ['flag_id'], ['id'])
    # ### end Alembic commands ###
