"""add environment to audit logs

Revision ID: 725dd9b9cbaf
Revises: ccd8bfdae18c
Create Date: 2026-09-11 12:56:25.493328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725dd9b9cbaf'
down_revision: Union[str, Sequence[str], None] = 'ccd8bfdae18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('environment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'environment')
    # ### end Alembic commands ###
