"""add user role

Revision ID: 8ba85b8475af
Revises: 5045a8affde2
Create Date: 2026-09-28 20:11:21.959613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba85b8475af'
down_revision: Union[str, Sequence[str], None] = '5045a8affde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('users', 'role')
#     # ### end Alembic commands ###


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(length=20),
            nullable=False,
            server_default='user'
        )
    )

    op.alter_column(
        'users',
        'role',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'role')