"""add user groups memberships and targeting rules

Revision ID: 927f8648a170
Revises: 9aefa1cbd5c2
Create Date: 2026-09-03 14:37:34.798956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927f8648a170'
down_revision: Union[str, Sequence[str], None] = '9aefa1cbd5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_group_name'), 'user_groups', ['group_name'], unique=True)
    op.create_index(op.f('ix_user_groups_id'), 'user_groups', ['id'], unique=False)
    op.create_table('targeting_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targeting_rules_flag_id'), 'targeting_rules', ['flag_id'], unique=False)
    op.create_index(op.f('ix_targeting_rules_id'), 'targeting_rules', ['id'], unique=False)
    op.create_table('user_group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group_membership')
    )
    op.create_index(op.f('ix_user_group_memberships_group_id'), 'user_group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_group_memberships_id'), 'user_group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_user_group_memberships_user_id'), 'user_group_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_group_memberships_user_id'), table_name='user_group_memberships')
    op.drop_index(op.f('ix_user_group_memberships_id'), table_name='user_group_memberships')
    op.drop_index(op.f('ix_user_group_memberships_group_id'), table_name='user_group_memberships')
    op.drop_table('user_group_memberships')
    op.drop_index(op.f('ix_targeting_rules_id'), table_name='targeting_rules')
    op.drop_index(op.f('ix_targeting_rules_flag_id'), table_name='targeting_rules')
    op.drop_table('targeting_rules')
    op.drop_index(op.f('ix_user_groups_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_group_name'), table_name='user_groups')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
