"""add rollout percentage to feature flags

Revision ID: ccd8bfdae18c
Revises: 927f8648a170
Create Date: 2026-09-04 18:21:04.674822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd8bfdae18c'
down_revision: Union[str, Sequence[str], None] = '927f8648a170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('rollout_percentage', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint('check_rollout_percentage', 'feature_flags', 'rollout_percentage >= 0 AND rollout_percentage <= 100')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_rollout_percentage', 'feature_flags', type_='check')
    op.drop_column('feature_flags', 'rollout_percentage')
    # ### end Alembic commands ###
